### PR TITLE
Increment pipeline version for new NCBI indices

### PR DESCRIPTION
**Pull request by gregdingle**
Although there is no code change to the main idseq pipeline, it seems like we should increment the version because the results will be different. 

Are there any more places the version should change? In idseq-web?

### CODE REVIEW

**Comment by jshoe** [comment]
I think we should lean on the alignment config being exposed, e.g. `PIPELINE v3.10, NT/NR: 2018-12-01| processed 2 hours ago` on the report page. Because in theory you could swap between different alignment databases, right?

**Comment by gregdingle** [comment]
Yes we could swap between different alignment databases, and I didn't see any increment of the pipeline version with NCBI updates in the past.

**Comment by gregdingle** [comment]
On the hand `PipelineVersionSelect` react component seems to support only the idseq-dag version, deduplicated, so it's not clear how a user would access multiple runs that differ by alignment config.

**Comment by jshoe** [comment]
> On the other hand `PipelineVersionSelect` react component seems to support only the idseq-dag version, deduplicated, so it's not clear how a user would access multiple runs that differ by alignment config.

That's true, maybe we should un-dedup by alignment configs

**Comment by gregdingle** [comment]
I added it to my list improvements for index updates here: https://czi.quip.com/QwMWAe4JXwu2/2019-09-25-Plan-to-automate-IDseq-index-generation.  

So do you think on balance it is better to increment the pipeline version or leave it as is?

**Comment by jshoe** [comment]
> So do you think on balance it is better to increment the pipeline version or leave it as is?

I think it's better to leave it as-is, and the behavior of the dropdown should pick the latest run among multiple if I recall correctly (if people request reruns).

**Comment by gregdingle** [comment]
Ok sounds good to me.

**Pull request closed without merging**
