### PR TITLE
discard last residual potentially sensitive reads

### PR DESCRIPTION
**Pull request by cdebourcy**
goes with https://github.com/chanzuckerberg/idseq-web/pull/2058

### CODE REVIEW

**Comment by jshoe** [comment]
@yunfangjuan is the concern that 'human' reads will become something else and the information will be lost? or that some will still slip through after reassignment?

**Comment by cdebourcy** [comment]
I thought I am dropping both the m8 records (used to make candidate db) and the reads themselves (annotated fasta). So the reads won't be considered at all in the continuation of the pipeline, no risk for spurious reassignment. Let me confirm and document the step dependencies real quick to make sure this is correct.

**Comment by yunfangjuan** [comment]
> @yunfangjuan is the concern that 'human' reads will become something else and the information will be lost? or that some will still slip through after reassignment?

the gsnap/rapsearch steps don't actually do any trimming. Its main purpose is to get  candidate accessions. The reads can still be assembled to something and be re-assigned. You can omit the human accessions for download but it doesn't mean the assembled contigs won't blast to human if you blast them directly

**Comment by yunfangjuan** [comment]
I had an offline discussion with @cdebourcy. This PR wouldn't actually achieve the intended goal. In addition, we are doing this for legal compliance not scientific rigor. It should be put in a separate sanitizing step either in the very beginning or the very end of the read assignment so people can use/read our code more easily.

**Pull request closed without merging**
