### PR TITLE
Refactored m8 summary to improve memory usage

### PR DESCRIPTION
**Pull request by morsecodist**
# Description

Another proposal for handling the memory usage issue. Alternative to https://github.com/chanzuckerberg/idseq-dag/pull/277. An issue with that approach is that it writes to disk which is slower than using memory. This PR combines the summary and ascensions accumulation steps to prevent the creation of two huge dicts and instead only create the much smaller summary dict. This could cut down the memory footprint dramatically without impacting performance.

This algorithm could be improved even more imo but I think this is the highest ROI change we can make right now.

# Version
- [x] I have increased the appropriate version number in https://github.com/chanzuckerberg/idseq-dag/blob/master/idseq_dag/__init__.py. Guidelines here: https://github.com/chanzuckerberg/idseq-dag/blob/pr-template/README.md#release-notes
- [x] I have added release notes for my new version to https://github.com/chanzuckerberg/idseq-dag/blob/master/README.md#release-notes
- [x] I will push a git tag after merging in the form `vX.Y.Z`

# Tests
Locally I compared this method to the old method running on real data from the pipeline. The results were identical.

I ran a memory profile with this real data for both versions. The results are here:

mem_profile

There was a slight slowdown, which is to be expected. We have ~3x memory usage decrease and ~1.25x speed decrease. 

I used the benchmark sample and took some sample rows to create a reproducible unit test for this functionality.

I ran this branch end to end (with the old alignment ASG logic and the new):

- Old Alighment logic: https://idseq.net/samples/46825
  (note: experimental failed due to a git branch pull issue, the logic is fine)
- New Alignment Logic Benchmark: https://idseq.net/samples/46762
- Single End FASTQ: https://idseq.net/samples/46763
- High Memory Sample, New Alignment Logic, No Subsampling: https://idseq.net/samples/46766

- [x] I have verified that the pipeline still completes successfully:
    - [x] for single-end inputs
    - [x] for paired-end inputs
    - [x] for FASTQ inputs
    - [x] for FASTA inputs.
- [x] I have validated that my change does not introduce any correctness bugs to existing output types.
- [x] I have validated that my change does not introduce significant performance regressions or I have discussed with the team that the benefits of the change are substantial enough that we're comfortable accepting the size of the measured performance penalty.

### CODE REVIEW

**Comment by kislyuk** [comment]
Let's add a unit test for this. (A simple Python unittest script in /test/test.py should do.)

**Comment by morsecodist** [comment]
@gregdingle @kislyuk Ran a unit test with real data comparing this to the other implementation and the results were identical. The old implementation froze my system though. I will create a test with a subset of the data and also do a quick memory profile.

**Comment by gregdingle** [comment]
@morsecodist After the unit test, we should do an end to end test. I've been testing my change with the fastq pair at s3://czb-covid-seqs/200331_A00111_0466_BH733TDSXY/G20_RR057e_00611_S311. See  https://idseq.net/samples/46706/pipeline_runs .

**Comment by morsecodist** [comment]
Running end to end test now

**Comment by morsecodist** [comment]
Passed the end to end test

**Comment by gregdingle** [comment]
Good stuff. I'll review later. In the meantime, I don't think it's a good idea to >1MB test files in the repo. Maybe put them in s3 and add a note to DL as needed?

**Comment by gregdingle** [comment]
Also, please link to the `pipeline_runs` page of the sample you tested end to end.

**Comment by morsecodist** [comment]
@gregdingle the sample links are in the description. I really don't want to need s3 credentials just to test the repo. I could make a smaller more targeted test, these were randomly selected, if I selected them in a targeted fashion I could test with small files.

**Comment by gregdingle** [comment]
@morsecodist , thanks I didn't look at the updated description. As for the test files, I would insist on a small set of test data <1MB, and some instructions on how to scale up the testing as needed.

**Comment by gregdingle** [comment]
The test run https://idseq.net/samples/46753 has subsampling turned at the default 2M. Although I don't have any reason to doubt that this PR will fix the OOM error, I would feel even better if it passed alignment with no subsampling on a sample known to fail otherwise. Thoughts?

**Comment by morsecodist** [comment]
@gregdingle sorry I am not sure what the correct subsampling setting is or how to disable it.

**Comment by gregdingle** [comment]
It's in the new admin options in web upload. See https://user-images.githubusercontent.com/28797/78460530-6c18bb00-7676-11ea-9ab3-b0c642003356.png .

**Comment by kislyuk** [comment]
What's the status on this? @morsecodist do you need any help?

**Comment by morsecodist** [comment]
Finally sorted out the testing, ready for review.

**Pull request merged**
